codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...80"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
    patch:
      default:
        target: auto
        threshold: 5%
        base: auto

ignore:
  - "**/*"
  - "!src/token"
  - "!src/lexer"
  - "!src/ast"
  - "!src/parser"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

github_checks:
  annotations: yes
