codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...80"

  status:
    project:
      default:
        target: auto
        threshold: 100%
        base: auto
    patch:
      default:
        target: 0%
        threshold: 100%
        base: auto

ignore:
  - "tests/**/*"
  - "src/main.c"
  - "src/ui/*"
  - "src/utils/*"
  - "src/utils/**/*"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

github_checks:
  annotations: yes
